config/routes.rb
Rails.application.routes.draw do

root 'static_pages#index'

match '/contacts',  to: 'contacts#new', via: 'get'
resources "contacts", only: [:new, :create]

match '/reportbug',  to: 'contacts#new', via: 'get'

match '/donate',  to: 'donations#new', via: 'get'
resources :donations, only: [:new, :create]

resources :teams, :path => "people" do
  resources :projects
end

resources :projects, :has_many => :blogs
resources :events, :has_many => :blogs

resources :users do
  resources :projects
  resources :blogs
end

match '/calendar',  to: 'events#index', via: 'get'

resources :user_sessions, only: [:new, :create, :destroy]

get 'login' => 'user_sessions#new'
get 'logout' => 'user_sessions#destroy'
  
match '/about', to:'static_pages#show', via:'get'

match '/contact', to:'contacts#new', via:'get'
resources "contacts", only: [:new, :create]

match '/media', to:'static_pages#under_construction', via:'get' 

get 'partners' => 'static_pages#partners'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
		#This is where our home page goes
		@teams = Team.all
	end	

	def show
		#This is where our about page goes
	end

	def under_construction
		#This is for the underconstruction page
	end

	def partners
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

    #
    # Creates an unordered list <ul> with a series of list items <li>
    # by calling the li function. This function takes a ruby hash containing
    # text/url pairs to use for the list items.
    #
    def ul (list)
        str = ''

        list.each_key do |i|
            str += li i, list[i]
        end

        return '<ul>' + str + '</ul>'

    end


    #
    # Creates a list item <li> and containing anchor tag <a href>.
    #
    def li (text, url)
        return '<li><a href=\'' + url + '\'>' + text + '</a></li>'
    end


end

app/views/static_pages/_footer.html.erb
<% 
	# if home page 
    footer_class = current_page?('/') ? 'home' : 'not-home' 
%>

<!-- this really should be necesary -->
<div style="height: 60px"></div>


<% if current_page?('/') %>
    <footer class="<%= footer_class %>">
            Copyright &copy <%= Time.new.year %> by Engineers Without Borders - UCF 

        <div class="goddamnit-i-hate-special-cases-<%= current_page?('/') ? 'home' : 'not-home'%>">
            <%= link_to "Report a bug!", reportbug_path %>
        </div>
    </footer>

<% else%>

    <footer class="<%= footer_class %>">
        <div class="col-md-4" style="text-align: left">
            Engineering 1, #144<br>
            4000 Central Florida Blvd. 
            Orlando, FL 32816
        </div>

        <div class="col-md-4" style="text-align: center;"> 
            Copyright &copy <%= Time.new.year %> <br> Engineers Without Borders - UCF 
        </div>

        <div class="col-md-4 goddamnit-i-hate-special-cases-<%= current_page?('/') ? 'home' : 'not-home'%>">
            <br><%= link_to "Report a bug!", reportbug_path %>
        </div>
    </footer>

<% end %>

app/views/static_pages/_nav.html.erb
<% 
    # if home page 
    home = current_page?('/') ? 'home' : 'not-home'

%>

<nav class="<%= home %>">
	
    <% # main logo for navbar %>
    <%= link_to image_tag("logo3.png"),  '/' %>


	<ul>
        <%= raw li 'About', '/about' %>

        <li> <%= link_to 'Our People', teams_path %>
    	    <ul>
                <span class="nav">
                    <%# FIX ME MCKINNLEY ROSE %>
                    <%# @teams.each do |t| %>
                        <%#= link_to t.name.titleize, team_path(t)%>
                    <%# end %>
                    <%= raw li 'Our Partners', '/partners' %>
                </span>
    	    </ul>	
        </li>

        <li> <%= link_to 'Our Projects', projects_path %></li>

	    <li> <%= link_to 'Media', '/media' %>
		    <ul>
                <span class="nav">
                    <%= raw li 'Photo', '/media/photo' %>
                    <%= raw li 'Video', '/media/video' %>
                </span>
		    </ul>
	    </li>

	    <li><%= link_to "Events", '/events' %>
            <ul>
                <span class="nav">
                    <%# FIX ME MCKINNLEY ROSE %>
                    <%# @events.each do |e| %>
                        <%#= link_to e.name.titleize, event_path(e)%>
                    <%# end %>
                </span>
            </ul>
        </li>
	    
        <%= raw li 'Contact', '/contact' %>
    </ul>
</nav>

app/views/static_pages/partners.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        EWB-UCF | Engineers Without Borders - University of Central Florida
    </title>
</head>
<body>

    <%= render "static_pages/nav" %>

    <div id="precontent"> Our Partners </div>

    <div id="content">

        <span style="float: left; width: 43%; padding: 3% 0%;">
            <%= image_tag "logo2.png", :width => "90%", :class => 'scfl-logo' %>
        </span>
        <span  style="width: 55%;">

            <p class="partner">
                <b>The Space Coast Florida Profesional Chapter</b> is a
                professional chapter of Engineers Without Borders - USA.
                EWB-USA is a nonprofit humanitarian organization 
                established to support community-driven development programs 
                worldwide through partnerships that design and implement 
                sustainable engineering projects, while creating transformative 
                experiences that enrich global perspectives and create 
                responsible leaders.
                <font style="color: #095aa6"> ... </font>
                <a href="#" class="resume">read more</a>
            </p>   
        </span>

        <% # uncomment when adding new pages %>
        <!-- <div class="divider"></div> -->  

    </div> <!-- content -->

    
    <div id="precontent" style="margin: 3% 0% 0% 0%;"> Our Sponsors </div>

    <div id="content">

        <%= image_tag "logo-ucoa.png"%>

    </div> <!-- content -->

    <%= render "static_pages/footer" %>
</body>
</html>

app/views/static_pages/show.html.erb
<div class="container-fluid precontent">About Us</div>

<div class="container-fluid content brown dark" style="height: 85%;">
	<div class="row">
		<h2 class="blue1">Engineers Without Borders - USA</h2>
		<p class="dark">
			Today, more than two billion people lack access to the most basic 
			things, such as clean drinking water, adequate sanitation, reliable 
			passage to local markets and more. Engineers Without Borders USA 
			(EWB-USA) is engineering change in 47 countries around the world to 
			change this reality -- one well at a time, one bridge at a time, 
			one community at a time.
		</p>
	</div>

	<br>

	<div class="row">
		<div class="col-md-7" >
			<b class="blue1" style="font-size: 14pt">
				Our mission:
			</b> 
			<p>
				EWB-USA is a nonprofit humanitarian organization established to 
				support <i class="green1"><b>community-driven</b></i> 
				development programs worldwide through partnerships that design 
				and implement sustainable engineering projects, while creating 
				transformative experiences that enrich global perspectives and 
				create responsible leaders.
			</p>
		</div>
		<div class="col-md-5">
			<b class="blue1" style="font-size: 14pt">
				Our vision:
			</b>
			<p>
				EWB-USA's vision is a world in which the communities we serve 
				have the capacity to sustainably meet their basic human needs.
			</p>
		</div>
	</div>

	<br><br>

	<div class="row" >
		EWB has 7 main types of projects:
	</div>

	<!-- Sorry :/ -->
	<!-- [TODO] fix this ... later -->
	<table>
	<tr>
		<td>
			<%= image_tag "icon-water-blue.png", :width => "75%"%>
			<p class="img"> Water Supply </p>
		</td>
		<td>
			<%= image_tag "icon-sanitation-blue.png", :width => "75%"%>
			<p class="img"> Sanitation </p>
		</td>
		<td>
			<%= image_tag "icon-civil-orange.png", :width => "75%"%>
			<p class="img"> Civil Works </p>
		</td>
		<td>
			<%= image_tag "icon-structures-green.png", :width => "75%"%>
			<p class="img"> Structures </p>
		</td>
		<td>
			<%= image_tag "icon-energy-yellow.png", :width => "75%"%>
			<p class="img"> Energy </p>
		</td>
		<td>
			<%= image_tag "icon-agriculture-grellow.png", :width => "75%"%>
			<p class="img"> Agriculture </p>
		</td>
		<td>
			<%= image_tag "icon-infosys-red.png", :width => "75%"%>
			<p class="img"> Information Systems </p>
		</td>
	</tr>
	</table>
</div> 

<div class="container-fluid content">
	<div class="row">
		<h2 class="blue1">EWB at the University of Central Florida</h2>
	</div>

	<div class="row">
		<div class="col-md-7" >
			<p>
				The UCF chapter was founded in 2007 and began its first project 
				in Mare Brignol, Haiti in early 2008. EWB-UCF implemented a water 
				quality and supply project from 2009 to 2011. Students from the UCF 
				chapter implemented 34 bio-sand	water filters and and a rain 
				catchement and water storage system in Mare Brignol. The project 
				formally concluded in 2013.
			</p>
			<p>
				The UCF chapter currently has a local aquaponics project in 
				Bithlo, FL and is in the process of working with organizations in
				the Dominican Republic to start a new international project in the 
				region. Our project teams pursue several additional side projects
				ranging from automatic weather stations and software to local 
				rain catchment projects.
			</p>
		</div>

		<div class="col-md-5 haiti-pic">
			<%= image_tag "haiti2.jpg", :width => "100%", :class => "haiti" %>
		</div>
	</div>
	
	<div class="divider"></div>

	<div class="row">
		<h2 class="blue1">Get Involved</h2>
	</div>
	<div class="row">
		<div class="col-md-12">
			<p>
				There are many ways to get involved in Engineers Without Borders.
				You can start by attending our general body meetings or other events
				to find out more about EWB and how you can get involved. We are 
				always accepting new members. Go to our
				<%= link_to 'events', '/events' %> page to find out about our 
				upcoming events and meetings. 
			</p>
			<p>
				You can still get involved if you're 
				not an engineering major. There are lots of opportunities to help 
				out, get involved, and make a difference!
			</p>
			<p>
				Check out our 
				<%= link_to 'Facebook page', 'https://www.facebook.com/EngineersWithoutBordersAtUcf' %>
				for more updates and announcements!
			</p>
		</div>
	</div>

</div> 

app/views/static_pages/under_construction.html.erb
    <div id="content" style="margin: 10% 0% 0% 0%;"></div> 


    <div id="precontent" style="text-align: center; margin: 0px 0px;"> 
        This Page is Under Construction
    </div>

    <div id="content"></div> 