config/routes.rb
Rails.application.routes.draw do

root 'static_pages#index'

match '/contacts',  to: 'contacts#new', via: 'get'
resources "contacts", only: [:new, :create]

match '/reportbug',  to: 'contacts#new', via: 'get'

match '/donate',  to: 'donations#new', via: 'get'
resources :donations, only: [:new, :create]

resources :teams, :path => "people" do
  resources :projects
end

resources :projects, :has_many => :blogs
resources :events, :has_many => :blogs

resources :users do
  resources :projects
  resources :blogs
end

match '/calendar',  to: 'events#index', via: 'get'

resources :user_sessions, only: [:new, :create, :destroy]

get 'login' => 'user_sessions#new'
get 'logout' => 'user_sessions#destroy'
  
match '/about', to:'static_pages#show', via:'get'

match '/contact', to:'contacts#new', via:'get'
resources "contacts", only: [:new, :create]

match '/media', to:'static_pages#under_construction', via:'get' 

get 'partners' => 'static_pages#partners'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  #validates :password, length: { minimum: 6 }
  validates_confirmation_of :password, message: "passwords should match", if: :password
  
  validates :email, uniqueness: true
  validates :username, uniqueness: true

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ['image/jpeg','image/png','image/jpg']

  has_and_belongs_to_many :teams
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :events
  
  has_many :blogs, :as => :bloggable

  #A user may have many applications
  #has_many :applications

  extend FriendlyId
  friendly_id :username, use: :slugged

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index]
  
  # GET /users
  # GET /users.json
  def index
      @users = User.all
  end

  # GET /users/1
  #FriendlyID /people/firstname
  def show
    #This is the users profile page
    @user = User.friendly.find(params[:id])


    #Needed to authorize CanCan
    authorize! :show, @user
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    #If users is the first user in the DB, they are admin
    if User.first == nil
      @user.role = "admin"
    elsif @user.role == nil
      @user.role = "user"
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'Your account has been created!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.role == "user"
      @user.role = "member"
      #@user.password = current_user.password
      #@user.password_confirmation = current_user.password_confirmation
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    def require_admin
      if current_user.role != "admin"
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role, :bio, :dob, :firstname, :lastname, :major, :minor, :subscription, :cvlink, :resumelink, :mysitelink, :graduation, :username, :email, :password, :password_confirmation, :image, :team_ids => [], :project_ids => [], :event_ids => [], :bloggable_ids => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# If user is first time user and has no role set up %>
  <%# they get a "user" %>
  <% if @user.role == nil %>
      <% @user.role = "user" %> 
  <% end %>

  <% if can? :manage, @user %>
    <%= f.check_box :role, :value => "member" %> 
    <%= f.label 'Member' %>

    <%= f.check_box :role, :value => "eboard" %> 
    <%= f.label 'EBoard' %>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.radio_button :subscription, 'student', :checked => true %><%= label :subscription_student, 'Student Weekly Newsletter' %>
    <%= f.radio_button :subscription, 'alum' %><%= label :subscription_alum, 'Alumni Monthly Newsletter' %>
    <%= f.radio_button :subscription, 'nil' %><%= label :subscription_alum, 'No Newsletter' %><br/>
  </div>

  <div class="field">
    <h6>Help us change the world, one community at a time!</h6>
  </div>

  <div class="actions">
    <%= f.submit "Create Free Account" %>
  </div>

<% end %>

app/views/users/_form_membership.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <%#CHANGE THIS MCKINNLEY ROSE TO PASSWORD REMEMBER ME? auto %>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  
  <p>
      <%= f.label :image, "Profile Pic" %><br />
      <%= f.file_field :image %>
  </p>

  <div class="field">
    <%= f.radio_button :subscription, 'student', :checked => true %> 
    <%= label :subscription_student, 'Student Weekly Newsletter' %><br/>
    <%= f.radio_button :subscription, 'alum' %> 
    <%= label :subscription_alum, 'Alumni Monthly Newsletter' %><br/>
    <%= f.radio_button :subscription, 'nil' %> 
    <%= label :subscription_alum, 'No Newsletter' %><br/>
  </div>

  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_field :dob %>
  </div>
  
  <div class="field">
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </div>

  <div class="field">
    <%= f.label :minor %><br>
    <%= f.text_field :minor %>
  </div>

  <div class="field">
    <%= f.label "About Me" %><br>
    <%= f.text_area :bio %>
  </div>
  
  <div class="field">
    <%= f.label :mysitelink, "Link to your personal site" %><br>
    <%= f.url_field :mysitelink %>
  </div>

  <div class="field">
    <%= f.label :cvlink, "Upload your CV" %><br>
    <%= f.url_field :cvlink %>
  </div>

  <div class="field">
    <%= f.label :resumelink, "Upload your Resume" %><br>
    <%= f.url_field :resumelink %>
  </div>

    <%"""Only Admin can change the role of the user """%>
    <% if can? :manage, @user %>
      <%= f.check_box :role, "admin" %>
      <%= label 'Admin' %>

      <%= f.check_box :role, "member", :checked => true %> 
      <%= label 'Member' %>

      <%= f.check_box :role, "eboard" %> 
      <%= label 'EBoard' %>

    <% end %>

  <div class="actions">
    <%= f.submit "Submit and Pay Dues" %>
  </div>

<% end %>

app/views/users/create.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        EWB-UCF | Engineers Without Borders - University of Central Florida
    </title>
</head>
<body>

    <%= render "static_pages/nav" %>

    <div id="precontent"> Congratulations!</div>

    <div id="content" style="overflow: hidden;">
		<%= link_to "Click here",  edit_user_path(@user) %> to become a member!

        <h6>Membership Benefits</h6>
        <ul>
            <li>Access to all online workshops and courseware</li>
            <li>Access to events</li>
            <li>Opportunity to apply for project teams</li>
            <li>Access to networking through the EWB Professional Chapter</li>
        </ul>

		<br/><br/>
		
    </div> <!-- content -->

    <%= render "static_pages/footer" %>
</body>
</html>

app/views/users/edit.html.erb
<div class="container-fluid precontent"> Update User </div>

<div class"container-fluid content" style="overflow: hidden;">
    <% if not logged_in? %>
    	flash.now.alert = "Please Login First"
    	<% link_to "Create Account", new_user_path %>
    <% else %>
    	<%= render 'form_membership' %>
    <% end %>

    <br/><br/>

    <%= link_to 'Back', users_path %>

</div> 

app/views/users/index.html.erb
<div class="container-fluid precontent"> All Users </div>

<div class="container-fluid content">

    <%= @users.each do |usr| %>
        <% if usr.role ||= "user" %>
            <h3><%= usr.role.titleize %></h3>
            <p><%= usr.username %></p>
            <p><%= usr.email %></p>
            <div class="divider"></div>  
        <% else %>
            <h3><%= usr.role.titleize %></h3>
            <p><%= usr.firstname %>, <%= usr.lastname %></p><br/>
            <%= link_to "View", user_path(usr)%>
            <%= usr.teams.each do |t| %>
                <%= t.name %><br/>
                <%= usr.major %><br/>
                <%= usr.bio %><br/>
            <% end %>
            <div class="divider"></div>  
        <% end %>
    <% end %>
    <div class="divider"></div>   

<% if can? :create, Project %>
    <%=link_to "Create new User", new_user_path %></br>
<% end %>  

</div> 

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        EWB-UCF | Engineers Without Borders - University of Central Florida
    </title>
</head>
<body>

    <div class="container-fluid precontent">
        Get Involved <h4 class="sub"> Change the world, one community at a time!</h4>
    </div>

    <div class="container-fluid content" style="overflow: hidden;">
        <%# User must login or signup to access the membership application %>
		<% if not logged_in? %>
			<%= render 'form' %>
        <% else %>
            <% render 'form_membership' %>
		<% end %>
    </div> 

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		EWB-UCF | Engineers Without Borders - University of Central Florida
	</title>
</head>
<body>
	<%#If current user role is user then they are the only ones that can see their own profile %>
	<%#but they can read everyones%>
	<% if @user.role == 'user' %>
		<% if current_user == @user %>
			<div class="container-fluid precontent">
		 		Welcome <h4 class="sub"><%= @user.username%></h4>
				<p>Become a <% link_to "member" %> and get a free profile page and blog!</p>
			</div>
		<% else %>
			<div class="container-fluid precontent">
		 		User: <h4 class="sub"><%= @user.username%></h4>
			</div>
		<% end %>
	<% else %>
		<%#If current user role is member then they can edit their own profile and see everyones%>
	 	<div class="container-fluid precontent">
	 		<%= @user.firstname %> <%= @user.lastname%>'s Profile<br/>
	 		<h4 class="sub"><%= @user.major%>, <%= @user.minor%></h4>

	 		<%# If user has a blog put a link to it, otherwise ask if they want to create it%>
	 		<% if @user.blogs.exists? %>
	 			<h4 class="sub"> <%= link_to "Create My Blog" , new_user_blog_path(@user) %></h4>
		 	<% else %>
		 		<h4 class="sub"> <%= link_to "My Blog" , polymorphic_url(@user), :method => :index %></h4>
		 	<% end %>

	 	<% if can? :edit, @user%>
	 		<p><%= link_to "Edit", edit_user_path%></p>
	 	<% end %>
	 </div>

	<div class="container-fluid content">
		
		<h2 style="margin: 0px 0px 10px 0px; float: left;">
			Bio
		</h2>
		<p class="about-ucf">
			<ul>
				<li><% @user.teams.each do |t| %></li>
				<li><%= t.title %></li>
				<% end %>
				<li>Role: <%= @user.role %></li>
			</ul>
			<p><%= @user.bio %></p>
			<br><br>
		</p>


		<p><%= @user.graduation %></p>
		<p><%= image_tag @user.image.url, :height => '180px', :class => 'tile' %></p>
		<%#if @user.resumelink?%>
			<a href="<% @user.resumelink %>"><%= @user.firstname%>'s Resume</a>
		<%# end %>
		<%#if @user.cvlink?%>
			<a href="<% @user.cvlink %>"><%= @user.firstname%>'s CV</a>
		<%# end %>


		<h2 style="margin: 0px 0px 10px 0px; float: left;">
			Projects
		</h2>
		<p class="about-ucf">
			<% @user.projects.each do |proj| %>
				<%= link_to proj.title, project_path(proj) %>
				<%= link_to proj.description, project_path(proj) %>
				<p><%= image_tag proj.image.url, :height => '180px', :class => 'tile'%></p>
			<% end %>
			<%# if user is logged in to their profile they see this%>
				<%= link_to "Add a New Project", new_project_path %>
			<%# end %>
			<br><br>
		</p>		

		
		<h2 style="margin: 0px 0px 10px 0px; float: left;">
			Workshops and Minicourses
		</h2>
		<p class="about-ucf">
			<%# @user.events.each do |event| %>
				<%#= link_to event.title, event_path(event) %>:<%#= link_to event.date %>
				<%#= link_to event.description, event_path(event) %>
				<p><%#= image_tag event.image.url, :height => '180px', :class => 'tile'%></p>
			<%# end %>
			<%# if user is logged in to their profile they see this%>
				<p>Is one of the events you attended not here? Email us for questions</p>
			<%# end %>
			<br><br>
		</p>		
	<% end %>

			<br><br><br>
		<div class="divider"></div>

	</div> <!-- content -->

	<%= render "static_pages/footer" %>
</body>
</html>