config/routes.rb
Rails.application.routes.draw do

root 'static_pages#index'

match '/contacts',  to: 'contacts#new', via: 'get'
resources "contacts", only: [:new, :create]

match '/reportbug',  to: 'contacts#new', via: 'get'

match '/donate',  to: 'donations#new', via: 'get'
resources :donations, only: [:new, :create]

resources :teams, :path => "people" do
  resources :projects
end

resources :projects, :has_many => :blogs
resources :events, :has_many => :blogs

resources :users do
  resources :projects
  resources :blogs
end

match '/calendar',  to: 'events#index', via: 'get'

resources :user_sessions, only: [:new, :create, :destroy]

get 'login' => 'user_sessions#new'
get 'logout' => 'user_sessions#destroy'
  
match '/about', to:'static_pages#show', via:'get'

match '/contact', to:'contacts#new', via:'get'
resources "contacts", only: [:new, :create]

match '/media', to:'static_pages#under_construction', via:'get' 

get 'partners' => 'static_pages#partners'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file:image
	validates_attachment_content_type :image, :content_type => ["image/jpeg","image/jpg","image/png"]

	belongs_to :team
	has_and_belongs_to_many :users

	has_and_belongs_to_many :donations
	
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	include ProjectsHelper

	#Require authentication for new, create, edit, destroy, update actions
	before_filter :require_login, except: [:index, :show]
	
	def index
		#Make projects accessible
		@projects = Project.all

		#Make teams accessible
		@teams = Team.all

		#Needed to authorize CanCan
    	authorize! :index, @projects
	end

	def show
		#This page shows all the projects of a certain type (local, international, software, etc)
		@project = Project.friendly.find(params[:id])

		#Needed to authorize CanCan
    	authorize! :show, @project
	end

	def new
		#This page allows only privilaged users to create new projects
		@project = Project.new

		#Make teams accessible
		@teams = Team.all
	end

	def create
		@project = Project.new(project_params)
		@project.save

		redirect_to project_path(@project)
	end

	def edit
		@project = Project.friendly.find(params[:id])
	end

	def update
		@project = Project.friendly.find(params[:id])
		@project.update(project_params)

		redirect_to project_path(@project)
	end

	def destroy
    	@project = Project.friendly.find(params[:id])
    	@project.destroy

    	redirect_to projects_path
  	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
	def project_params
		params.require(:project).permit(:title, :category, :team_id, :about, :description, :status, :image, :user_ids => [], :donation_ids => [], :bloggable_ids => [])
	end
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {multipart: false}) do |p| %>
  <ul> <% @project.errors.full_messages.each do |error| %>  
  <li><%= error %></li>
  <% end %>
</ul>
  
<h3>What is the title of this project?</h3>
<p>
  <%= p.label :title %><br />
  <%= p.text_field :title %>
</p>

<h3>What team is working on this project?</h3>
<p>
  <% if @teams == [] %>
    <%# McKinnley Rose. Fix this shit. %>
    <strong>WARNING: A team must be created first</strong>
  <% end %>
  <%# List the teams and check the teams available%>
  <% @teams.each do |t| %>
    <%= p.radio_button(:team_id, t.id) %> 
    <%= label :team_id, t.name %><br/>
  <% end %>
</p>

<h3>What is the general mission of this project?</h3>
<p>
  <%= p.label :about %><br />
  <%= p.text_area :about %>
</p>

<h3>Describe more specifically what the project entails?</h3>
<p>
  <%= p.label :description %><br />
  <%= p.text_area :description %>
</p>
 
<h3>What is the current status of the project?</h3>
<p>
  <%= p.label :status %><br />
  <%= p.text_area :status %>
</p>

<p>
  <%= p.label :image, "Project logo" %><br />
  <%= p.file_field :image %>
</p>

<p>
  <%= p.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<%= render partial: 'form' %>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        EWB-UCF | Engineers Without Borders - University of Central Florida
    </title>
</head>
<body>
    <div class="container-fluid precontent">Insert Text Here</div>

    <%= render "static_pages/nav" %>

    <div id="precontent"> Our Projects
    </div>

    <div id="content" style="overflow: hidden;">

	<% @teams.each do |team| %>
            <div id="local">
            <%  %>
        	<li><%= link_to team.project.title, team_project_path(team)%></li>
        	<p><%= team.project.description %></p>

            <% if can? :manage, Project %>
                <p><%= link_to "Edit", edit_team_project_path(team) %> | 
                <%=link_to "Delete", team_project_path(team), method: :delete, data: {confirm: "Really delete the project?"}%>
            <% end %>
            </div>
        <% end %>

	<% if can? :create, Project %>
	<%=link_to "Create new project", new_project_path %></br>
	<% end %>
        
    </div> <!-- content -->

    <%= render "static_pages/footer" %>
</body>
</html>

app/views/projects/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        EWB-UCF | Engineers Without Borders - University of Central Florida
    </title>
</head>
<body>
    <div class="container-fluid precontent">Insert Text Here</div>

    <%= render "static_pages/nav" %>

    <div id="precontent"> Create A New Project
    </div>

    <div id="content" style="overflow: hidden;">
		<%= render partial: 'form' %>
	
    </div> <!-- content -->

    <%= render "static_pages/footer" %>
</body>
</html>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        EWB-UCF | Engineers Without Borders - University of Central Florida
    </title>
</head>
<body>

    <%= render "static_pages/nav" %>

    <div id="precontent"> 
    	<%= @project.title %> 
    	<p><%= link_to "Edit", edit_project_path(@project) %>

		<%=link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Really delete the project?"}%>
		</p>

        <p><%= link_to 'Support this project!', new_donation_path %></p>
    </div>

    <div id="content" style="overflow: hidden;">

        <p><%= @project.description %></p>

    	<%# Display the project image if it exists%>
        <% if @project.image_file_name != nil %>
			<p><%= image_tag @project.image.url %></p>
		<% end %>

    </div> <!-- content -->
    <%= render "static_pages/footer" %>

</body>
</html>