config/routes.rb
Rails.application.routes.draw do

root 'static_pages#index'

match '/contacts',  to: 'contacts#new', via: 'get'
resources "contacts", only: [:new, :create]

match '/reportbug',  to: 'contacts#new', via: 'get'

match '/donate',  to: 'donations#new', via: 'get'
resources :donations, only: [:new, :create]

resources :teams, :path => "people" do
  resources :projects
end

resources :projects, :has_many => :blogs
resources :events, :has_many => :blogs

resources :users do
  resources :projects
  resources :blogs
end

match '/calendar',  to: 'events#index', via: 'get'

resources :user_sessions, only: [:new, :create, :destroy]

get 'login' => 'user_sessions#new'
get 'logout' => 'user_sessions#destroy'
  
match '/about', to:'static_pages#show', via:'get'

match '/contact', to:'contacts#new', via:'get'
resources "contacts", only: [:new, :create]

match '/media', to:'static_pages#under_construction', via:'get' 

get 'partners' => 'static_pages#partners'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EWB-UCF | Engineers Without Borders</title> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%#= render "static_pages/nav" %>

	<h6 class="row <%= current_page?('/') ? 'login1' : 'login2'%>">
		<% if logged_in? %>
		  Welcome, <%= link_to current_user.username, user_path(current_user), class: "username"%>! 

            <% if current_page?('/') %>
                <br><br>
            <% end %>

		  <%= link_to "Become a Member!", edit_user_path(current_user) %>  
		  <%= link_to "Logout", logout_path %>

		<% else %>
		  <%= link_to "Login", login_path %> or <%= link_to "Sign Up", new_user_path %>
		<% end %>
		<br/>
	</h6>

    <%- flash.each do |key, msg| -%>
		<div id="<%= key %>">
		<p><%= msg %></p>
		<div class=""></div>
		</div>
	<%- end -%>

	<%#= link_to "Donate!", new_project_donation_path('nil') %>

    <%= render "static_pages/nav" %>

	<%= yield %>
    
    <div class="container-fluid content-last"></div>
    <%= render "static_pages/footer" %>
    

</body>
</html>